# These are link ids
# from https://musicbrainz.org/relationships/artist-url

ARTIST_PURCHASE_FOR_DOWNLOAD: str = "176"
ARTIST_DOWNLOAD_FOR_FREE: str = "177"
ARTIST_FREE_STREAMING: str = "194"
ARTIST_STREAMING: str = "978"
ARTIST_BANDCAMP: str = "718"
ARTIST_YOUTUBE_MUSIC: str = "1080"
ARTIST_DISCOGS: str = "180"
ARTIST_OTHER_DATABASES: str = "188"
RELEASE_PURCHASE_FOR_DOWNLOAD: str = "74"
RELEASE_DOWNLOAD_FOR_FREE: str = "75"
RELEASE_FREE_STREAMING: str = "85"
RELEASE_STREAMING: str = "980"
RELEASE_DISCOGS: str = "76"
RELEASE_OTHER_DATABASES: str = "82"
